cours_bon$optionnel[cours_bon$optionnel%in% "FALSE"]<- "FAUX"
View(cours_bon)
cours_bon$optionnel[cours_bon$optionnel%in% "TRUE"]<- "VRAI"
View(cours_bon)
cours_bon$optionnel[cours_bon$optionnel%in% "Faux"]<- "FAUX"
View(cours_bon)
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "mael_guerin"]<-"mael_gerin"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "marie_burghin"]<-"marie_bughin"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "philippe_barette"]<-"philippe_barrette" 
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "phillippe"]<-"philippe"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "sabrina_leclerc"]<-"sabrine_leclercq"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "samule"]<-"samuel"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "yannick"]<-"yanick"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "sagneau"]<-"sageau"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% c("harbeck bastien","harbeck_bastien")]<-"harbeck-bastien"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "arianne_barette"]<-"ariane_barrette"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "francis_bolly"]<-"francis_boily"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "ihuoma_elsie-ebere"]<-"ihuoma_elsie_ebere"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "jonathan_rondeau_leclaire"]<-"jonathan_rondeau-leclaire"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "kayla_trempe-kay"]<-"kayla_trempe_kay"
etudiant_bon$prenom_nom[etudiant_bon$prenom_nom%in% "peneloppe_robert"]<-"penelope_robert"
